#### Input 5 subject marks from user and display grade.(first class,second class)

sub1= int(input('enter the sub1:'))
sub2= int(input('enter the sub2:'))
sub3= int(input('enter the sub3:'))
sub4= int(input('enter the sub4:'))
sub5= int(input('enter the sub5:'))

total =(sub1+ sub2+ sub3+ sub4+ sub5)

if (total > 250):
  print('A first class:')


else:
 print('B second class:')



